---
name: Build and Push Frontend and Backend to Google Cloud
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to Google Container Registry
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE: frontend
      BACKEND_IMAGE: backend
      PROJECT_ID: caramel-hallway-333402
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Build Frontend
        run: |-
          cd frontend
          docker build -t $FRONTEND_IMAGE:latest .

      - name: Build Backend
        run: |-
          cd backend
          docker build -t $BACKEND_IMAGE:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker Images to Container Registry (GCR)
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $FRONTEND_IMAGE:latest gcr.io/$PROJECT_ID/$FRONTEND_IMAGE
          docker push gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:latest

          docker tag $BACKEND_IMAGE:latest gcr.io/$PROJECT_ID/$BACKEND_IMAGE
          docker push gcr.io/$PROJECT_ID/$BACKEND_IMAGE:latest
